### ISSUE TITLE
Update openlexington.org

### ISSUE THREAD

**Issue by mikedillion** [openlexington/OpenLexington#44]
All information can be found in the [2015 OpenLexington 
Strategic Plan](https://docs.google.com/a/codeforamerica.org/document/d/1Es1dNIENTQswtVaaOyT7w5dHY98pSup66_9WhmbeCwA/edit?usp=sharing).
- [x] [add code of conduct to website](https://github.com/openlexington/openlexington.org/issues/12)
- [ ] [add list of core team members](https://github.com/openlexington/openlexington.org/issues/13)
- [ ] [add municipal partners](https://github.com/openlexington/openlexington.org/issues/14)
- [ ] [add community partners](https://github.com/openlexington/openlexington.org/issues/15)

**Comment by chaserx** [comment]
I also want to update the website style... but that's another issue.

**Comment by bFraley** [comment]
I've submitted a [pull request](https://github.com/openlexington/openlexington.org/pull/27) that resolves the remaining tasks for this issue.
